### ISSUE TITLE
Fatal:perl:die Perl died in LaTeXML::Post::XMath

### ISSUE THREAD

**Issue by tkw1536** [KWARC/LaTeXML#3] opened 2015-03-13 16:02 UTC
I get: 

```
(XMath wilsonquotient.omdoc 2 to process...Fatal:post:generic Post-processor crashed! 
Fatal:perl:die Perl died
	Postprocessing LaTeXML::Post::XMath wilsonquotient.omdoc
	Can't locate object method "getAttribute" via package "XML::LibXML::Text" at /path/to/localmh/ext/perl5lib/lib/perl5/LaTeXML/Post.pm line 440.

Status:conversion:3 
```

**Comment by dginev** [comment] 2015-03-13 16:10
Give us a TeX snippet and exact LaTeXML invocation to reproduce this, otherwise we can't help (safe from making that exact piece of code a little bit more defensive, but that would treat the symptom, not the cause)

**Comment by kohlhase** [comment] 2015-04-09 19:06
I get the same with ```.../MathHub/smglom/sets/source/image.de.tex```: 
```
lmh gen --omdoc image.de.tex
Checking modules, this may take a while ...
Found 1 paths to work on. 
OMDOC: Less jobs then available workers, using fewer workers. 
OMDOC: 1 file(s) to generate using 1 worker. 
OMDOC: Generating /path/to/localmh/MathHub/smglom/sets/source/image.de.omdoc
1 warning; 11 errors
Error! Did not write file /path/to/localmh/MathHub/smglom/sets/source/image.de.omdoc
OMDOC: Did not generate /path/to/localmh/MathHub/smglom/sets/source/image.de.omdoc
OMDOC: Generated 0 file(s), failed 1 file(s). 
Michaels-MBP:source kohlhase$ pwd
/Users/kohlhase/localmh/MathHub/smglom/sets/source
```
@dginev It would be great, if you could have a look

**Comment by m-iancu** [comment] 2015-04-13 11:44
you can maybe get a list from here: https://mathhub.info/mh/common-errors?types=3&compilers=latexml  (click `show all` for  `perl died`).

**Comment by brucemiller** [comment] 2015-04-16 14:27
Just guessing since things seem out-of-sync, but I *may* have fixed what causes this in the main LaTeXML.

**Comment by dginev** [comment] 2015-04-16 14:28
Merging into KWARC/LaTeXML now, then they can retry.

**Comment by dginev** [comment] 2015-04-16 14:55
Merged and still highly experimental.

**Closed** 2015-04-20 23:04 UTC
